export class OutputQueue {}
export class SpooledFile {}
export class SpooledFileOutputStream {}
export class Printer {}
export class PrinterFile {}
export class WriterJob {}
export class AFPResource {}
export class PrintObject {}
export class PrintParameterList {}
